name: vietfuel_shared
description: Shared models and utilities for VietFuel applications (staff app and supplier app).
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^6.0.0
  logger: ^1.4.0
